// Structured agenda data with timing, events, and venues
export const agendaData = [
  {
    dayNumber: 0,
    date: "Wednesday, 25/02/2026",
    title: "Day 0 - Inauguration & Movie Night",
    events: [
      { timing: "05:00 PM – 05:03 PM", name: "Tamil Thai Vazhthu", venue: "Main Stage" },
      { timing: "05:03 PM – 05:08 PM", name: "Lighting The Kuthuvilaku", venue: "Main Stage" },
      { timing: "05:08 PM – 05:13 PM", name: "Welcome Address", venue: "Main Auditorium" },
      { timing: "05:13 PM – 05:18 PM", name: "Inaugural Address", venue: "Main Auditorium" },
      { timing: "05:18 PM – 05:23 PM", name: "Presidential Address", venue: "Main Auditorium" },
      { timing: "05:23 PM – 05:38 PM", name: "Chief Guest Speech", venue: "Main Auditorium" },
      { timing: "05:38 PM – 05:41 PM", name: "Felicitation", venue: "Main Stage" },
      { timing: "05:41 PM – 05:44 PM", name: "Vote of Thanks", venue: "Main Auditorium" },
      { timing: "05:44 PM – 06:00 PM", name: "Classical Performance", venue: "Main Stage" },
      { timing: "06:00 PM – 06:10 PM", name: "Silambam Performance", venue: "Main Stage" },
      { timing: "06:10 PM – 07:00 PM", name: "Movie Team", venue: "Main Auditorium" },
      { timing: "07:20 PM – 10:00 PM", name: "Movie Night", venue: "Main Auditorium" },
    ],
  },
  {
    dayNumber: 1,
    date: "Thursday, 26/02/2026",
    title: "Day 1 - Concert Night & Workshops",
    events: [
      { timing: "10:30 AM – 12:30 PM", name: "Intra Group Dance", venue: "Vivek Auditorium" },
      { timing: "01:30 PM – 02:30 PM", name: "Solo Dance", venue: "Vivek Auditorium" },
      { timing: "02:30 PM – 04:00 PM", name: "Duo Dance", venue: "Vivek Auditorium" },
      { timing: "10:30 AM – 01:00 PM", name: "Saptham Workshop", venue: "Ada Lovelace Auditorium" },
      { timing: "06:30 PM – 10:00 PM", name: "Concert", venue: "Main Stage" },
    ],
  },
  {
    dayNumber: 2,
    date: "Friday, 27/02/2026",
    title: "Day 2 - T Awards",
    events: [
      { timing: "10:30 AM – 12:30 PM", name: "Stand-up Comedy", venue: "Vivek Auditorium" },
      { timing: "01:00 PM – 02:00 PM", name: "Solo Singing", venue: "Vivek Auditorium" },
      { timing: "02:00 PM – 03:30 PM", name: "Battle of Bands", venue: "Vivek Auditorium" },
      { timing: "10:30 AM – 01:00 PM", name: "GT Workshop", venue: "Ada Lovelace Auditorium" },
      { timing: "06:30 PM – 06:45 PM", name: "Cheers Music", venue: "Main Stage" },
      { timing: "06:45 PM – 07:15 PM", name: "Lyricist Karunakaran Song Release", venue: "Main Stage" },
      { timing: "07:15 PM – 10:15 PM", name: "T Awards", venue: "Main Auditorium" },
      { timing: "08:00 PM – 08:10 PM", name: "Intra Group Dance Winners", venue: "Main Stage" },
      { timing: "08:45 PM – 09:10 PM", name: "Spartanz", venue: "Main Stage" },
    ],
  },
  {
    dayNumber: 3,
    date: "Saturday, 28/02/2026",
    title: "Day 3 - Choreo & Finale",
    events: [
      { timing: "10:30 AM – 12:30 PM", name: "Mime Competition", venue: "Vivek Auditorium" },
      { timing: "01:00 PM – 02:30 PM", name: "Intra Variety Competition", venue: "Vivek Auditorium" },
      { timing: "02:30 PM – 04:00 PM", name: "Inter Variety Competition", venue: "Vivek Auditorium" },
      { timing: "10:30 AM – 11:30 AM", name: "Nadopasana", venue: "Ada Lovelace Auditorium" },
      { timing: "11:30 AM – 12:30 PM", name: "Nrithyopasana", venue: "Ada Lovelace Auditorium" },
      { timing: "05:30 PM – 06:00 PM", name: "Sruthilaya", venue: "Main Stage" },
      { timing: "06:00 PM – 07:45 PM", name: "Choreo Night", venue: "Main Stage" },
      { timing: "07:45 PM – 08:00 PM", name: "Twisters", venue: "Main Stage" },
      { timing: "08:00 PM – 08:20 PM", name: "Intra Variety Winners", venue: "Main Stage" },
      { timing: "08:20 PM – 09:40 PM", name: "Talent of Techofes", venue: "Main Auditorium" },
      { timing: "09:40 PM – 10:00 PM", name: "DJ Night", venue: "Main Stage" },
    ],
  },
];
