const eventData = {
  "Signature Events": [
    {
      id: 1,
      title:"Intra Group Dance",
      category: "Competition",
      description: "Expert discussions on latest technologies and innovations.",
      dateMonth: "FEB",
      dateDay: "26",
      fullDate: "Feb 26, 2026",
      time: "10:30 - 12:30 PM",
      venue: "Vivekanandha Auditorium",
      entryFee: "₹100 / Head",
      cashPrize: "Up to ₹10,000",
      rulesImage: '/images/rules/group_d.png',
      posterImage: '/images/poster/intra-grp.png',
      registrationLink: 'https://docs.google.com/forms/d/e/1FAIpQLSd9W10A8AZG7YTHs_mYVDq6NQT44pPh9ZD1cubT2dxRb8OSFw/viewform'
    },
    {
      id: 10,
      title: "Abinaya Workshop",
      category: "WORKSHOP",
      description: "Learn the concepts and types of Abinaya.",
      dateMonth: "FEB",
      dateDay: "26",
      fullDate: "Feb 26, 2026",
      time: "1:30 - 4:00 PM",
      venue: "Ada Lovelace Auditorium",
      entryFee: "Free",
      cashPrize: "-",
      registrationLink: 'https://docs.google.com/forms/d/e/1FAIpQLSfpDaK2sQ5glU8RC73pv8LtRlyibiIjwPph3lUGDD2cB0vHYA/viewform'
    },
    {
      id: 11,
      title: "Parai Workshop",
      category: "WORKSHOP",
      description: "Learn the concepts and types of Abinaya.",
      dateMonth: "FEB",
      dateDay: "26",
      fullDate: "Feb 26, 2026",
      time: "1:30 - 4:00 PM",
      venue: "Seminar Hall, CEG Square, 1st Floor",
      entryFee: "Free",
      cashPrize: "-",
      registrationLink: 'https://docs.google.com/forms/d/e/1FAIpQLSeXA6WeuAsKrya8j8mFyiv5BhQtvsQUlZNzEYCe8W_DSV1krA/viewform'
    },
    {
      id: 2,
      title: "Solo Dance",
      category: "COMPETITION",
      description: "Compete in live coding competitions with top developers.",
      dateMonth: "FEB",
      dateDay: "26",
      fullDate: "Feb 26, 2026",
      time:  "1:30 - 2:30 PM",
      venue: "Vivekanandha Auditorium",
      entryFee: "₹200 / Head",
      cashPrize: "Up to ₹7,500 ",
      rulesImage: ['/images/rules/solo_d.png','/images/rules/sol_d_2.png'],
      posterImage: '/images/poster/Solo-dance.png',
      registrationLink: 'https://docs.google.com/forms/d/e/1FAIpQLSfqzxXoMGaSTh6QzL0aP5CPr1Q9LrYN4izTwE6Ih49t_m8fzw/viewform'
    },
    {
      id: 3,
      title: "Duo Dance",
      category: "COMPETITION",
      description: "Share your innovative ideas with industry leaders.",
      dateMonth: "FEB",
      dateDay: "26",
      fullDate: "Feb 26, 2026",
      time: "2:30 - 4:00 PM",
      venue: "Vivekanandha Auditorium",
      entryFee: "₹300 / Team of 2",
      cashPrize: "Up to ₹7,500",
      rulesImage: '/images/rules/duo_d.jpg',
      posterImage: '/images/poster/Duo-dance.png',
      registrationLink: 'https://docs.google.com/forms/d/e/1FAIpQLSdrjCJI7ATMWXQPjw2wMCJ_ZYxILfmmkSjFxz17cF_-o0MK3w/viewform'
    },
    {
      id: 4,
      title: "Standup Comedy",
      category: "SHOW",
      description: "24-hour coding marathon to build amazing projects.",
      dateMonth: "FEB",
      dateDay: "27",
      fullDate: "Feb 27, 2026",
      time: "10:30 - 12:30 PM",
      venue: "Vivekanandha Auditorium",
      entryFee: "Free",
      cashPrize: "-",
      registrationLink: ''
    },
    {
      id: 5,
      title: "Solo Singing",
      category: "COMPETITION",
      description: "Inspiring talks from industry leaders about future trends.",
      dateMonth: "FEB",
      dateDay: "27",
      fullDate: "Feb 27, 2026",
      time: "1:00 - 2:00 PM",
      venue: "Vivekanandha Auditorium",
      entryFee: "₹200 / Head",
      cashPrize: "₹10,000",
      rulesImage: '/images/rules/solo_s_2.png',
      posterImage: '/images/poster/solo-sing.png',
      registrationLink: 'https://docs.google.com/forms/d/e/1FAIpQLSfzqB09JkNqirQh-0mhUWxHZmXbbBTMjwMDXVoy4nUbeHCejQ/viewform'
    },
    {
      id: 6,
      title: "Battle of Bands",
      category: "COMPETITION",
      description: "Inspiring talks from industry leaders about future trends.",
      dateMonth: "FEB",
      dateDay: "27",
      fullDate: "Feb 27, 2026",
      time: "2:00 - 3:30 PM",
      venue: "Vivekanandha Auditorium",
      entryFee: "₹200 / Head",
      cashPrize: "₹15,000",
      rulesImage: '/images/rules/botb_2.png',
      posterImage: '/images/poster/Bob.png',
      registrationLink: 'https://docs.google.com/forms/d/e/1FAIpQLSeo2wuBv4fiKkHEmqyjfwqv0_7m--1ZpcRlVg3MQ5MbIb6LrQ/viewform'
    },
    {
      id: 7,
      title: "Comic Arena",
      category: "COMPETITION",
      description: "Inspiring talks from industry leaders about future trends.",
      dateMonth: "FEB",
      dateDay: "28",
      fullDate: "Feb 28, 2026",
      time: "10:30 - 12:30 PM",
      venue: "Vivekanandha Auditorium",
      entryFee: "Free",
      cashPrize: "TBA",
      rulesImage: ['/images/rules/comic_1.png','/images/rules/comic_2.png'],
      registrationLink: 'https://docs.google.com/forms/d/e/1FAIpQLSf62iHatYsDf-eCaWVBhF_iIxB660Uq1V8SLOOzMkEScrK-4w/viewform?pli=1'
    },
    {
      id: 8,
      title: "Intra College Variety Competition",
      category: "COMPETITION",
      description: "Inspiring talks from industry leaders about future trends.",
      dateMonth: "FEB",
      dateDay: "28",
      fullDate: "Feb 28, 2026",
      time: "1:00 - 2:30 PM",
      venue: "Vivekanandha Auditorium",
      entryFee: "₹1000/ Team",
      cashPrize: "Up to ₹10,000",
      rulesImage: ['/images/rules/intra_college_2.png','/images/rules/intra_3.png'],
      posterImage: '/images/poster/intra.png',
      registrationLink: 'https://docs.google.com/forms/d/e/1FAIpQLSepMvhUaLJpM9xM1y8Ela4grxxx1oEdoFdvCDza29QYo8MHJg/viewform'
    },
    {
      id: 9,
      title: "Inter College Variety Competition",
      category: "COMPETITION",
      description: "Inspiring talks from industry leaders about future trends.",
      dateMonth: "FEB",
      dateDay: "28",
      fullDate: "Feb 28, 2026",
      time: "2:30 - 4:00 PM",
      venue: "Vivekanandha Auditorium",
      entryFee: "₹2000/ Team",
      cashPrize: "Up to ₹20,000",
      rulesImage: ['/images/rules/inter_2.png','/images/rules/Inter_3.png'],
      posterImage: '/images/poster/inter.png',
      registrationLink: 'https://docs.google.com/forms/d/e/1FAIpQLSeKVNOpGzA0MQUGbetVC56oCW2iQ0xi-EXvH5KjVxSR4_9Ouw/viewform'
    },
  ],
  "ProShows": [
    {
      id: 1,
      title: "Movie Night",
      category: "Movie",
      description: "Learn professional shoe design from industry experts.",
      dateMonth: "FEB",
      dateDay: "25",
      fullDate: "FEB 25, 2026",
      time: "7:20 - 10:00 PM",
      venue: "Sports Gallery",
      entryFee: "Free",
      cashPrize: "-",
    },
    {
      id: 2,
      title: "Concert Night",
      category: "Fun",
      description: "Browse and experience latest shoe collections worldwide.",
      dateMonth: "FEB",
      dateDay: "26",
      fullDate: "Feb 26, 2026",
      time: "6:30 - 10:00 PM",
      venue: "Sports Gallery",
      entryFee: "₹300",
      cashPrize: "N/A",
      registrationLink: 'https://docs.google.com/forms/d/e/1FAIpQLSfiK_uFhjaOMW1Ai_xTmyLQ_AewNMxv8YaGe9A7-ZVmMIo9Wg/viewform',
      posterImage: '/images/posters/concert_night.jpeg'
    },
    {
      id: 3,
      title: "T - Awards",
      category: "Awards",
      description: "",
      dateMonth: "FEB",
      dateDay: "27",
      fullDate: "Feb 27, 2026",
      time: "7:15 - 10:15 PM",
      venue: "Sports Gallery",
      entryFee: "₹2000",
      cashPrize: "N/A",
      registrationLink: 'https://docs.google.com/forms/d/e/1FAIpQLScr3oTVO9zjtQkEp9Iex3rcbXlwShWLXstdCwwwnGA3X2IZBg/viewform',
      posterImage: '/images/posters/choreo_night.jpeg'
    },
    {
      id: 4,
      title: "Choreo Night",
      category: "Fun",
      description: "Witness the latest footwear trends on the runway.",
      dateMonth: "FEB",
      dateDay: "28",
      fullDate: "Feb 28, 2026",
      time: "6:00 - 10:45 PM",
      venue: "Sports Gallery",
      entryFee: "₹500",
      cashPrize: "N/A",
      registrationLink: 'https://docs.google.com/forms/d/e/1FAIpQLScr3oTVO9zjtQkEp9Iex3rcbXlwShWLXstdCwwwnGA3X2IZBg/viewform',
      posterImage: '/images/posters/choreo_night.jpeg'
    },
    {
      id: 5,
      title: "Talent of Techofes",
      category: "Fun",
      description: "Understanding ergonomic and comfortable footwear design.",
      dateMonth: "FEB",
      dateDay: "28",
      fullDate: "Feb 28, 2026",
      time: "8:20 - 9:40 PM",
      venue: "Sports Gallery",
      entryFee: "Free",
      cashPrize: "Merch Prizes",
      registrationLink: ''
    }
  ],
  "Red Building Events": [
    {
      id: 1,
      title: "Heritage Tour",
      category: "TOUR",
      description: "Explore the historical architecture and stories of heritage.",
      dateMonth: "NOV",
      dateDay: "15",
      fullDate: "Nov 15, 2026",
      time: "10:00 AM",
      venue: "Red Building",
      entryFee: "Free",
      cashPrize: "N/A"
    },
    {
      id: 2,
      title: "Architecture Seminar",
      category: "SEMINAR",
      description: "Learn about classic and modern architectural techniques.",
      dateMonth: "NOV",
      dateDay: "16",
      fullDate: "Nov 16, 2026",
      time: "2:00 PM",
      venue: "Red Building",
      entryFee: "₹300",
      cashPrize: "Certificates"
    },
    {
      id: 3,
      title: "Cultural Performance",
      category: "PERFORMANCE",
      description: "Traditional arts and cultural showcase.",
      dateMonth: "NOV",
      dateDay: "17",
      fullDate: "Nov 17, 2026",
      time: "5:00 PM",
      venue: "Red Building",
      entryFee: "₹200",
      cashPrize: "N/A"
    },
    {
      id: 4,
      title: "Photo Walk",
      category: "ACTIVITY",
      description: "Capture architectural beauty through guided photography.",
      dateMonth: "NOV",
      dateDay: "18",
      fullDate: "Nov 18, 2026",
      time: "9:00 AM",
      venue: "Red Building",
      entryFee: "Free",
      cashPrize: "N/A"
    },
    {
      id: 5,
      title: "Historical Lecture",
      category: "LECTURE",
      description: "Discover the fascinating stories behind the building.",
      dateMonth: "NOV",
      dateDay: "19",
      fullDate: "Nov 19, 2026",
      time: "4:00 PM",
      venue: "Red Building",
      entryFee: "Free",
      cashPrize: "N/A"
    }
  ],
  "Carnival": [
    {
      id: 1,
      title: "Game Stalls",
      category: "GAMES",
      description: "Experience exciting carnival games with amazing prizes.",
      dateMonth: "DEC",
      dateDay: "05",
      fullDate: "Dec 5, 2026",
      time: "12:00 PM",
      venue: "Carnival Grounds",
      entryFee: "₹100/game",
      cashPrize: "Worth ₹50,000"
    },
    {
      id: 2,
      title: "Food Festival",
      category: "FOOD",
      description: "Delicious street food and cuisines from around the world.",
      dateMonth: "DEC",
      dateDay: "05",
      fullDate: "Dec 5, 2026",
      time: "1:00 PM",
      venue: "Food Court",
      entryFee: "Variable",
      cashPrize: "N/A"
    },
    {
      id: 3,
      title: "Rides & Attractions",
      category: "RIDES",
      description: "Thrilling carnival rides and attractions for all ages.",
      dateMonth: "DEC",
      dateDay: "06",
      fullDate: "Dec 6, 2026",
      time: "3:00 PM",
      venue: "Amusement Zone",
      entryFee: "₹50-500",
      cashPrize: "N/A"
    },
    {
      id: 4,
      title: "Entertainment Shows",
      category: "SHOW",
      description: "Live performances, magic shows and entertainment acts.",
      dateMonth: "DEC",
      dateDay: "06",
      fullDate: "Dec 6, 2026",
      time: "6:00 PM",
      venue: "Main Stage",
      entryFee: "Free",
      cashPrize: "N/A"
    },
    {
      id: 5,
      title: "Prize Booth",
      category: "GAMES",
      description: "Win amazing merchandise and exclusive prizes.",
      dateMonth: "DEC",
      dateDay: "07",
      fullDate: "Dec 7, 2026",
      time: "2:00 PM",
      venue: "Central Area",
      entryFee: "Variable",
      cashPrize: "Worth ₹2,00,000"
    }
  ],
  "Night Shows": [
    {
      id: 1,
      title: "Concert Night",
      category: "CONCERT",
      description: "Live music performances from popular artists.",
      dateMonth: "DEC",
      dateDay: "15",
      fullDate: "Dec 15, 2026",
      time: "7:00 PM",
      venue: "Amphitheater",
      entryFee: "₹500-1500",
      cashPrize: "N/A"
    },
    {
      id: 2,
      title: "DJ Night",
      category: "DJ NIGHT",
      description: "High-energy electronic music with renowned DJs.",
      dateMonth: "DEC",
      dateDay: "16",
      fullDate: "Dec 16, 2026",
      time: "9:00 PM",
      venue: "Night Club",
      entryFee: "₹800",
      cashPrize: "N/A"
    },
    {
      id: 3,
      title: "Theater Performance",
      category: "THEATER",
      description: "Dramatic stage presentations and theatrical performances.",
      dateMonth: "DEC",
      dateDay: "17",
      fullDate: "Dec 17, 2026",
      time: "8:00 PM",
      venue: "Main Theater",
      entryFee: "₹300-600",
      cashPrize: "N/A"
    },
    {
      id: 4,
      title: "Stargazing Event",
      category: "ASTRONOMY",
      description: "Astronomical observations and celestial wonders.",
      dateMonth: "DEC",
      dateDay: "18",
      fullDate: "Dec 18, 2026",
      time: "10:00 PM",
      venue: "Observatory",
      entryFee: "₹200",
      cashPrize: "N/A"
    },
    {
      id: 5,
      title: "Dance Night",
      category: "DANCE",
      description: "Learn and groove to various dance styles.",
      dateMonth: "DEC",
      dateDay: "19",
      fullDate: "Dec 19, 2026",
      time: "8:30 PM",
      venue: "Dance Floor",
      entryFee: "₹400",
      cashPrize: "N/A"
    }
  ]
};

export default eventData;