const eventData = {
  "Signature Events": [
    {
      id: 1,
      title:"Intra Group Dance",
      category: "Competition",
      description: "Expert discussions on latest technologies and innovations.",
      dateMonth: "FEB",
      dateDay: "26",
      fullDate: "Feb 26, 2026",
      time: "10:30 - 12:30 PM",
      venue: "Vivekanandha Auditorium",
      entryFee: "₹100 / Head",
      cashPrize: "Up to ₹10,000",
      rulesImage: '/images/rules/group_d.png',
      posterImage: '/images/poster/intra-grp.png',
      registrationLink: 'https://docs.google.com/forms/d/e/1FAIpQLSd9W10A8AZG7YTHs_mYVDq6NQT44pPh9ZD1cubT2dxRb8OSFw/viewform'
    },
    {
      id: 10,
      title: "Abinaya Workshop",
      category: "WORKSHOP",
      description: "Learn the concepts and types of Abinaya.",
      dateMonth: "FEB",
      dateDay: "26",
      fullDate: "Feb 26, 2026",
      time: "1:30 - 4:00 PM",
      venue: "Ada Lovelace Auditorium",
      entryFee: "Free",
      cashPrize: "-",
      registrationLink: 'https://docs.google.com/forms/d/e/1FAIpQLSfpDaK2sQ5glU8RC73pv8LtRlyibiIjwPph3lUGDD2cB0vHYA/viewform'
    },
    {
      id: 11,
      title: "Parai Workshop",
      category: "WORKSHOP",
      description: "Learn the concepts and types of Abinaya.",
      dateMonth: "FEB",
      dateDay: "26",
      fullDate: "Feb 26, 2026",
      time: "1:30 - 4:00 PM",
      venue: "Seminar Hall, CEG Square, 1st Floor",
      entryFee: "Free",
      cashPrize: "-",
      registrationLink: 'https://docs.google.com/forms/d/e/1FAIpQLSeXA6WeuAsKrya8j8mFyiv5BhQtvsQUlZNzEYCe8W_DSV1krA/viewform'
    },
    {
      id: 2,
      title: "Solo Dance",
      category: "COMPETITION",
      description: "Compete in live coding competitions with top developers.",
      dateMonth: "FEB",
      dateDay: "26",
      fullDate: "Feb 26, 2026",
      time:  "1:30 - 2:30 PM",
      venue: "Vivekanandha Auditorium",
      entryFee: "₹200 / Head",
      cashPrize: "Up to ₹7,500 ",
      rulesImage: ['/images/rules/solo_d.png','/images/rules/sol_d_2.png'],
      posterImage: '/images/poster/Solo-dance.png',
      registrationLink: 'https://docs.google.com/forms/d/e/1FAIpQLSfqzxXoMGaSTh6QzL0aP5CPr1Q9LrYN4izTwE6Ih49t_m8fzw/viewform'
    },
    {
      id: 3,
      title: "Duo Dance",
      category: "COMPETITION",
      description: "Share your innovative ideas with industry leaders.",
      dateMonth: "FEB",
      dateDay: "26",
      fullDate: "Feb 26, 2026",
      time: "2:30 - 4:00 PM",
      venue: "Vivekanandha Auditorium",
      entryFee: "₹300 / Team of 2",
      cashPrize: "Up to ₹7,500",
      rulesImage: '/images/rules/duo_d.jpg',
      posterImage: '/images/poster/Duo-dance.png',
      registrationLink: 'https://docs.google.com/forms/d/e/1FAIpQLSdrjCJI7ATMWXQPjw2wMCJ_ZYxILfmmkSjFxz17cF_-o0MK3w/viewform'
    },
    {
      id: 4,
      title: "Standup Comedy",
      category: "SHOW",
      description: "24-hour coding marathon to build amazing projects.",
      dateMonth: "FEB",
      dateDay: "27",
      fullDate: "Feb 27, 2026",
      time: "10:30 - 12:30 PM",
      venue: "Vivekanandha Auditorium",
      entryFee: "Free",
      cashPrize: "-",
      registrationLink: ''
    },
    {
      id: 5,
      title: "Solo Singing",
      category: "COMPETITION",
      description: "Inspiring talks from industry leaders about future trends.",
      dateMonth: "FEB",
      dateDay: "27",
      fullDate: "Feb 27, 2026",
      time: "1:00 - 2:00 PM",
      venue: "Vivekanandha Auditorium",
      entryFee: "₹200 / Head",
      cashPrize: "₹10,000",
      rulesImage: '/images/rules/solo_s_2.png',
      posterImage: '/images/poster/solo-sing.png',
      registrationLink: 'https://docs.google.com/forms/d/e/1FAIpQLSfzqB09JkNqirQh-0mhUWxHZmXbbBTMjwMDXVoy4nUbeHCejQ/viewform'
    },
    {
      id: 6,
      title: "Battle of Bands",
      category: "COMPETITION",
      description: "Inspiring talks from industry leaders about future trends.",
      dateMonth: "FEB",
      dateDay: "27",
      fullDate: "Feb 27, 2026",
      time: "2:00 - 3:30 PM",
      venue: "Vivekanandha Auditorium",
      entryFee: "₹200 / Head",
      cashPrize: "₹15,000",
      rulesImage: '/images/rules/botb_2.png',
      posterImage: '/images/poster/Bob.png',
      registrationLink: 'https://docs.google.com/forms/d/e/1FAIpQLSeo2wuBv4fiKkHEmqyjfwqv0_7m--1ZpcRlVg3MQ5MbIb6LrQ/viewform'
    },
    {
      id: 7,
      title: "Comic Arena",
      category: "COMPETITION",
      description: "Inspiring talks from industry leaders about future trends.",
      dateMonth: "FEB",
      dateDay: "28",
      fullDate: "Feb 28, 2026",
      time: "10:30 - 12:30 PM",
      venue: "Vivekanandha Auditorium",
      entryFee: "Free",
      cashPrize: "TBA",
      rulesImage: ['/images/rules/comic_1.png','/images/rules/comic_2.png'],
      registrationLink: 'https://docs.google.com/forms/d/e/1FAIpQLSf62iHatYsDf-eCaWVBhF_iIxB660Uq1V8SLOOzMkEScrK-4w/viewform?pli=1'
    },
    {
      id: 8,
      title: "Intra College Variety Competition",
      category: "COMPETITION",
      description: "Inspiring talks from industry leaders about future trends.",
      dateMonth: "FEB",
      dateDay: "28",
      fullDate: "Feb 28, 2026",
      time: "1:00 - 2:30 PM",
      venue: "Vivekanandha Auditorium",
      entryFee: "₹1000/ Team",
      cashPrize: "Up to ₹10,000",
      rulesImage: ['/images/rules/intra_college_2.png','/images/rules/intra_3.png'],
      posterImage: '/images/poster/intra.png',
      registrationLink: 'https://docs.google.com/forms/d/e/1FAIpQLSepMvhUaLJpM9xM1y8Ela4grxxx1oEdoFdvCDza29QYo8MHJg/viewform'
    },
    {
      id: 9,
      title: "Inter College Variety Competition",
      category: "COMPETITION",
      description: "Inspiring talks from industry leaders about future trends.",
      dateMonth: "FEB",
      dateDay: "28",
      fullDate: "Feb 28, 2026",
      time: "2:30 - 4:00 PM",
      venue: "Vivekanandha Auditorium",
      entryFee: "₹2000/ Team",
      cashPrize: "Up to ₹20,000",
      rulesImage: ['/images/rules/inter_2.png','/images/rules/Inter_3.png'],
      posterImage: '/images/poster/inter.png',
      registrationLink: 'https://docs.google.com/forms/d/e/1FAIpQLSeKVNOpGzA0MQUGbetVC56oCW2iQ0xi-EXvH5KjVxSR4_9Ouw/viewform'
    },
  ],
  "ProShows": [
    {
      id: 1,
      title: "Movie Night",
      category: "Movie",
      description: "Learn professional shoe design from industry experts.",
      dateMonth: "FEB",
      dateDay: "25",
      fullDate: "FEB 25, 2026",
      time: "7:20 - 10:00 PM",
      venue: "Sports Gallery",
      entryFee: "Free",
      cashPrize: "-",
    },
    {
      id: 2,
      title: "Concert Night",
      category: "Fun",
      description: "Browse and experience latest shoe collections worldwide.",
      dateMonth: "FEB",
      dateDay: "26",
      fullDate: "Feb 26, 2026",
      time: "6:30 - 10:00 PM",
      venue: "Sports Gallery",
      entryFee: "₹300",
      cashPrize: "N/A",
      registrationLink: 'https://docs.google.com/forms/d/e/1FAIpQLSfiK_uFhjaOMW1Ai_xTmyLQ_AewNMxv8YaGe9A7-ZVmMIo9Wg/viewform',
      posterImage: '/images/posters/concert_night.jpeg'
    },
    {
      id: 3,
      title: "T - Awards",
      category: "Awards",
      description: "",
      dateMonth: "FEB",
      dateDay: "27",
      fullDate: "Feb 27, 2026",
      time: "7:15 - 10:15 PM",
      venue: "Sports Gallery",
      entryFee: "₹2000",
      cashPrize: "N/A",
      registrationLink: 'https://docs.google.com/forms/d/e/1FAIpQLScr3oTVO9zjtQkEp9Iex3rcbXlwShWLXstdCwwwnGA3X2IZBg/viewform',
      posterImage: '/images/posters/choreo_night.jpeg'
    },
    {
      id: 4,
      title: "Choreo Night",
      category: "Fun",
      description: "Witness the latest footwear trends on the runway.",
      dateMonth: "FEB",
      dateDay: "28",
      fullDate: "Feb 28, 2026",
      time: "6:00 - 10:45 PM",
      venue: "Sports Gallery",
      entryFee: "₹500",
      cashPrize: "N/A",
      registrationLink: 'https://docs.google.com/forms/d/e/1FAIpQLScr3oTVO9zjtQkEp9Iex3rcbXlwShWLXstdCwwwnGA3X2IZBg/viewform',
      posterImage: '/images/posters/choreo_night.jpeg'
    },
    {
      id: 5,
      title: "Talent of Techofes",
      category: "Fun",
      description: "Understanding ergonomic and comfortable footwear design.",
      dateMonth: "FEB",
      dateDay: "28",
      fullDate: "Feb 28, 2026",
      time: "8:20 - 9:40 PM",
      venue: "Sports Gallery",
      entryFee: "Free",
      cashPrize: "Merch Prizes",
      registrationLink: ''
    }
  ],
  "Red Building Events": [
    {
      id: 1,
      title: "Informals",
      dateMonth: "FEB",
      dateDay: "26",
      fullDate: "Feb 26, 2026",
      venue: "Chemistry Deptartment",
      timing: "10:30 AM - 12:30 PM",
      //posterImage: '/images/events/ACM/Trade smart. Adapt fast. Survive the market..png'
    },
    {
      id: 2,
      title: "IPL Auction",
      dateMonth: "FEB",
      dateDay: "26",
      fullDate: "Feb 26, 2026",
      venue: "Red Building",
      round1Timing: "10:30 AM - 12:30 PM",
      round2Timing: "1:45 PM - 4:00 PM",
      hallNumber: "Hall 72",
      posterImage: '/images/events/ipl auction.jpeg'

    },
    {
      id: 3,
      title: "Meme Quiz",
      dateMonth: "FEB",
      dateDay: "26",
      fullDate: "Feb 26, 2026",
      venue: "Red Building",
      round1Timing: "10:30 AM - 12:30 PM",
      round2Timing: "1:45 PM - 4:00 PM",
      hallNumber: "Hall 73",
      posterImage: '/images/events/QA/2.jpg'
    },
    {
      id: 4,
      title: "Case Files: Unsolved",
      dateMonth: "FEB",
      dateDay: "26",
      fullDate: "Feb 26, 2026",
      venue: "Red Building",
      round1Timing: "10:30 AM - 12:30 PM",
      round2Timing: "1:45 PM - 4:00 PM",
      hallNumber: "Hall 74",
      posterImage: '/images/events/ACM/SAVE_20260218_232909.jpg'
    },
    {
      id: 5,
      title: "Lyric by lyric",
      dateMonth: "FEB",
      dateDay: "26",
      fullDate: "Feb 26, 2026",
      venue: "Red Building",
      round1Timing: "10:30 AM - 12:30 PM",
      round2Timing: "1:45 PM - 4:00 PM",
      hallNumber: "Hall 75",
      posterImage: '/images/events/Sruthilaya AU/RB_E1_lyric-by-lyric.png'
    },
    {
      id: 6,
      title: "Riddle rush",
      dateMonth: "FEB",
      dateDay: "26",
      fullDate: "Feb 26, 2026",
      venue: "Red Building",
      round1Timing: "10:30 AM - 12:30 PM",
      round2Timing: "1:45 PM - 4:00 PM",
      hallNumber: "Hall 76",
      posterImage: '/images/events/CSAU/Riddle Rush.png'
    },
    {
      id: 7,
      title: "Synesthesia",
      dateMonth: "FEB",
      dateDay: "26",
      fullDate: "Feb 26, 2026",
      venue: "Red Building",
      round1Timing: "10:30 AM - 12:30 PM",
      round2Timing: "1:45 PM - 4:00 PM",
      hallNumber: "Hall 81",
      posterImage: '/images/events/Saptham/Saptham 1.png'
    },
    {
      id: 8,
      title: "One-minute movie from hell",
      dateMonth: "FEB",
      dateDay: "26",
      fullDate: "Feb 26, 2026",
      venue: "Red Building",
      round1Timing: "10:30 AM - 12:30 PM",
      round2Timing: "1:45 PM - 4:00 PM",
      hallNumber: "Hall 82",
      posterImage: '/images/events/AUP/AUP.png'
    },
    {
      id: 9,
      title: "Circle Conquest",
      dateMonth: "FEB",
      dateDay: "26",
      fullDate: "Feb 26, 2026",
      venue: "Red Building",
      round1Timing: "10:30 AM - 12:30 PM",
      round2Timing: "1:45 PM - 4:00 PM",
      hallNumber: "Hall 83",
      posterImage: '/images/events/The Guindy Times/Circle Conquest.png'
    },
    {
      id: 10,
      title: "Inside the thought bubble",
      dateMonth: "FEB",
      dateDay: "26",
      fullDate: "Feb 26, 2026",
      venue: "Red Building",
      round1Timing: "10:30 AM - 12:30 PM",
      round2Timing: "1:45 PM - 4:00 PM",
      hallNumber: "Hall 84",
      posterImage: '/images/events/The Emotional Intelligence (EQ) Club/inside the thought bubble event poster.jpeg'
    },
    {
      id: 11,
      title: "Genre Roulette",
      dateMonth: "FEB",
      dateDay: "26",
      fullDate: "Feb 26, 2026",
      venue: "Red Building",
      round1Timing: "10:30 AM - 12:30 PM",
      round2Timing: "1:45 PM - 4:00 PM",
      hallNumber: "Hall 9",
      posterImage: '/images/events/Thetron/Thetron 1.png'
    },
    {
      id: 12,
      title: "Waste Wonders",
      dateMonth: "FEB",
      dateDay: "26",
      fullDate: "Feb 26, 2026",
      venue: " Veranda near Drawing Hall",
      round1Timing: "10:30 AM - 12:30 PM",
      round2Timing: "1:45 PM - 4:00 PM",
      hallNumber: "Hall 13",
      posterImage: '/images/events/GB/GB_WasteWonders (3).png'
    },
    {
      id: 13,
      title: "Silent Synergy",
      dateMonth: "FEB",
      dateDay: "26",
      fullDate: "Feb 26, 2026",
      venue: "Drawing Hall",
      round1Timing: "10:30 AM - 12:30 PM",
      round2Timing: "1:45 PM - 4:00 PM",
      hallNumber: "Hall 10",
      posterImage: '/images/events/Castle Red/Castle Red 2.jpeg'
    },
    {
      id: 14,
      title: "Trust the Frame",
      dateMonth: "FEB",
      dateDay: "26",
      fullDate: "Feb 26, 2026",
      venue: "Quadrangle",
      round1Timing: "10:30 AM - 12:30 PM",
      round2Timing: "1:45 PM - 4:00 PM",
      hallNumber: "Hall 10",
      posterImage: '/images/events/Pixels/PIXELS 1 TRUST THE FRAME (11).png'
    },
    {
      id: 15,
      title: "Informals",
      dateMonth: "FEB",
      dateDay: "27",
      fullDate: "Feb 27, 2026",
      venue: "Chemistry Department",
      round1Timing: "10:30 AM - 12:30 PM",
      round2Timing: "1:45 PM - 4:00 PM",
      hallNumber: "Hall 10"
    },
    {
      id: 16,
      title: "The Photograph That Should Not Exist",
      dateMonth: "FEB",
      dateDay: "27",
      fullDate: "Feb 27, 2026",
      venue: "Red Building ",
      round1Timing: "10:30 AM - 12:30 PM",
      round2Timing: "1:45 PM - 4:00 PM",
      hallNumber: "Hall 72",
      posterImage: '/images/events/Pixels/PIXELS_2.O.png'
    },
    {
      id: 17,
      title: "Costume Designing",
      dateMonth: "FEB",
      dateDay: "27",
      fullDate: "Feb 27, 2026",
      venue: "Red Building",
      round1Timing: "10:30 AM - 12:30 PM",
      round2Timing: "1:45 PM - 4:00 PM",
      hallNumber: "Hall 73",
      //posterImage:
    },
    {
      id: 18,
      title: "Great tradeoff",
      dateMonth: "FEB",
      dateDay: "27",
      fullDate: "Feb 27, 2026",
      venue: "Red Building",
      round1Timing: "10:30 AM - 12:30 PM",
      round2Timing: "1:45 PM - 4:00 PM",
      hallNumber: "Hall 74",
      posterImage: '/images/events/ACM/Trade smart. Adapt fast. Survive the market..png'
    },
    {
      id: 19,
      title: "Dance memory game",
      dateMonth: "FEB",
      dateDay: "27",
      fullDate: "Feb 27, 2026",
      venue: "Red Building",
      round1Timing: "10:30 AM - 12:30 PM",
      round2Timing: "1:45 PM - 4:00 PM",
      hallNumber: "Hall 75",
      posterImage: '/images/events/Saptham/Saptham 2.png'
    },
    {
      id: 20,
      title: "Triple threat",
      dateMonth: "FEB",
      dateDay: "27",
      fullDate: "Feb 27, 2026",
      venue: "Red Building",
      round1Timing: "10:30 AM - 12:30 PM",
      round2Timing: "1:45 PM - 4:00 PM",
      hallNumber: "Hall 76",
      posterImage: '/images/events/LEO/LEO_2Triple threat.png'
    },
    {
      id: 21,
      title: "Kollywood clash ",
      dateMonth: "FEB",
      dateDay: "27",
      fullDate: "Feb 27, 2026",
      venue: "Red Building",
      round1Timing: "10:30 AM - 12:30 PM",
      round2Timing: "1:45 PM - 4:00 PM",
      hallNumber: "Hall 81",
      posterImage: '/images/events/The Guindy Times/Kollywood Clash.png'
    },
    {
      id: 22,
      title: "Letters never sent",
      dateMonth: "FEB",
      dateDay: "27",
      fullDate: "Feb 27, 2026",
      venue: "Red Building",
      round1Timing: "10:30 AM - 12:30 PM",
      round2Timing: "1:45 PM - 4:00 PM",
      hallNumber: "Hall 82",
      posterImage: '/images/events/AUP/AUP2.png'
    },
    {
      id: 23,
      title: "Predict and Profit",
      dateMonth: "FEB",
      dateDay: "27",
      fullDate: "Feb 27, 2026",
      venue: "Red Building",
      round1Timing: "10:30 AM - 12:30 PM",
      round2Timing: "1:45 PM - 4:00 PM",
      hallNumber: "Hall 83",
      //posterImage:
    },
    {
      id: 24,
      title: "Assassin",
      dateMonth: "FEB",
      dateDay: "27",
      fullDate: "Feb 27, 2026",
      venue: "Red Building",
      round1Timing: "10:30 AM - 12:30 PM",
      round2Timing: "1:45 PM - 4:00 PM",
      hallNumber: "Hall 84",
      posterImage: '/images/events/LIT/LIT1.png'
    },
    {
      id: 25,
      title: "Nobody can stop me",
      dateMonth: "FEB",
      dateDay: "27",
      fullDate: "Feb 27, 2026",
      venue: "Red Building",
      round1Timing: "10:30 AM - 12:30 PM",
      round2Timing: "1:45 PM - 4:00 PM",
      hallNumber: "Hall 9",
      posterImage: '/images/events/AstroClub/Nobody Can Stop Me.jpeg'
    },
    {
      id: 26,
      title: "Art Mayhem",
      dateMonth: "FEB",
      dateDay: "27",
      fullDate: "Feb 27, 2026",
      venue: "Veranda near Drawing Hall",
      round1Timing: "10:30 AM - 12:30 PM",
      round2Timing: "1:45 PM - 4:00 PM",
      hallNumber: "Hall 13",
      posterImage: '/images/events/Scribbles/Scribbles_2.jpeg'
    },
    {
      id: 27,
      title: "Power Exchange",
      dateMonth: "FEB",
      dateDay: "27",
      fullDate: "Feb 27, 2026",
      venue: "Drawing Hall",
      round1Timing: "10:30 AM - 12:30 PM",
      round2Timing: "1:45 PM - 4:00 PM",
      hallNumber: "Hall 10",
      posterImage: '/images/events/Castle Red/Castle Red 2.jpeg'
    },
    {
      id: 28,
      title: " Informals",
      dateMonth: "FEB",
      dateDay: "28",
      fullDate: "Feb 28, 2026",
      venue: "Chemistry Department",
      round1Timing: "10:30 AM - 12:30 PM",
      round2Timing: "1:45 PM - 4:00 PM",
      hallNumber: "Hall 10",
    },
    {
      id: 29,
      title: "Music feud",
      dateMonth: "FEB",
      dateDay: "28",
      fullDate: "Feb 28, 2026",
      venue: "Red Building",
      round1Timing: "10:30 AM - 12:30 PM",
      round2Timing: "1:45 PM - 4:00 PM",
      hallNumber: "Hall 72",
      posterImage: '/images/events/Sruthilaya AU/RB_E2_Music fued.png'
    },
    {
      id: 30,
      title: " General Quiz",
      dateMonth: "FEB",
      dateDay: "28",
      fullDate: "Feb 28, 2026",
      venue: "Red Building",
      round1Timing: "10:30 AM - 12:30 PM",
      round2Timing: "1:45 PM - 4:00 PM",
      hallNumber: "Hall 73",
      posterImage: '/images/events/QA/1.jpg'
    },
    {
      id: 31,
      title: "Improve",
      dateMonth: "FEB",
      dateDay: "28",
      fullDate: "Feb 28, 2026",
      venue: "Red Building",
      round1Timing: "10:30 AM - 12:30 PM",
      round2Timing: "1:45 PM - 4:00 PM",
      hallNumber: "Hall 74",
      posterImage: '/images/events/Thetron/Thetron 2.png'
    },
    {
      id: 32,
      title: "Tamil Movie Auction",
      dateMonth: "FEB",
      dateDay: "28",
      fullDate: "Feb 28, 2026",
      venue: "Red Building",
      round1Timing: "10:30 AM - 12:30 PM",
      round2Timing: "1:45 PM - 4:00 PM",
      hallNumber: "Hall 75",
      posterImage: '/images/events/LIT/LIT2.png'
    },
    {
      id: 33,
      title: "Movie Script",
      dateMonth: "FEB",
      dateDay: "28",
      fullDate: "Feb 28, 2026",
      venue: "Red Building",
      round1Timing: "10:30 AM - 12:30 PM",
      round2Timing: "1:45 PM - 4:00 PM",
      hallNumber: "Hall 76",
      //posterImage:
    },
    {
      id: 34,
      title: "Quality Bingo",
      dateMonth: "FEB",
      dateDay: "28",
      fullDate: "Feb 28, 2026",
      venue: "Red Building",
      round1Timing: "10:30 AM - 12:30 PM",
      round2Timing: "1:45 PM - 4:00 PM",
      hallNumber: "Hall 81",
      posterImage: '/images/events/SQC/SQC.jpeg'
    },
    {
      id: 35,
      title: "EQ Lightning Round",
      dateMonth: "FEB",
      dateDay: "28",
      fullDate: "Feb 28, 2026",
      venue: "Red Building",
      round1Timing: "10:30 AM - 12:30 PM",
      round2Timing: "1:45 PM - 4:00 PM",
      hallNumber: "Hall 82",
      posterImage: '/images/events/The Emotional Intelligence (EQ) Club/inside the thought bubble event poster.jpeg'
    },
    {
      id: 36,
      title: "Cook with AI",
      dateMonth: "FEB",
      dateDay: "28",
      fullDate: "Feb 28, 2026",
      venue: "Red Building",
      round1Timing: "10:30 AM - 12:30 PM",
      round2Timing: "1:45 PM - 4:00 PM",
      hallNumber: "Hall 83",
      posterImage: '/images/events/CSAU/Cook with ai.png'
    },
    {
      id: 37,
      title: "Guess the link",
      dateMonth: "FEB",
      dateDay: "28",
      fullDate: "Feb 28, 2026",
      venue: "Red Building",
      round1Timing: "10:30 AM - 12:30 PM",
      round2Timing: "1:45 PM - 4:00 PM",
      hallNumber: "Hall 84",
      posterImage: '/images/events/LEO/LEO_1guess the link.png'
    },
    {
      id: 38,
      title: "Eco Pictionary",
      dateMonth: "FEB",
      dateDay: "28",
      fullDate: "Feb 28, 2026",
      venue: "Red Building",
      round1Timing: "10:30 AM - 12:30 PM",
      round2Timing: "1:45 PM - 4:00 PM",
      hallNumber: "Hall 9",
      posterImage: '/images/events/GB/GB_Ecopictionary.png'
    },
    {
      id: 39,
      title: " Beat drop, Brush drop",
      dateMonth: "FEB",
      dateDay: "28",
      fullDate: "Feb 28, 2026",
      venue: "varanda near Drawing Hall",
      round1Timing: "10:30 AM - 12:30 PM",
      round2Timing: "1:45 PM - 4:00 PM",
      hallNumber: "Hall 13",
      posterImage: '/images/events/Scribbles/Scribbles_1.jpeg'
    },
    {
      id: 40,
      title: "Aim and Fire your Planet",
      dateMonth: "FEB",
      dateDay: "28",
      fullDate: "Feb 28, 2026",
      venue: "Quadrangle",
      round1Timing: "10:30 AM - 12:30 PM",
      round2Timing: "1:45 PM - 4:00 PM",
      hallNumber: "Hall 10",
      posterImage: '/images/events/AstroClub/Aim and Fire Your Planet.jpg'
    },

  ],
  "Carnival": [
    {
      id: 1,
      title: "Game Stalls",
      category: "GAMES",
      description: "Experience exciting carnival games with amazing prizes.",
      dateMonth: "DEC",
      dateDay: "05",
      fullDate: "Dec 5, 2026",
      time: "12:00 PM",
      venue: "Carnival Grounds",
      entryFee: "₹100/game",
      cashPrize: "Worth ₹50,000"
    },
    {
      id: 2,
      title: "Food Festival",
      category: "FOOD",
      description: "Delicious street food and cuisines from around the world.",
      dateMonth: "DEC",
      dateDay: "05",
      fullDate: "Dec 5, 2026",
      time: "1:00 PM",
      venue: "Food Court",
      entryFee: "Variable",
      cashPrize: "N/A"
    },
    {
      id: 3,
      title: "Rides & Attractions",
      category: "RIDES",
      description: "Thrilling carnival rides and attractions for all ages.",
      dateMonth: "DEC",
      dateDay: "06",
      fullDate: "Dec 6, 2026",
      time: "3:00 PM",
      venue: "Amusement Zone",
      entryFee: "₹50-500",
      cashPrize: "N/A"
    },
    {
      id: 4,
      title: "Entertainment Shows",
      category: "SHOW",
      description: "Live performances, magic shows and entertainment acts.",
      dateMonth: "DEC",
      dateDay: "06",
      fullDate: "Dec 6, 2026",
      time: "6:00 PM",
      venue: "Main Stage",
      entryFee: "Free",
      cashPrize: "N/A"
    },
    {
      id: 5,
      title: "Prize Booth",
      category: "GAMES",
      description: "Win amazing merchandise and exclusive prizes.",
      dateMonth: "DEC",
      dateDay: "07",
      fullDate: "Dec 7, 2026",
      time: "2:00 PM",
      venue: "Central Area",
      entryFee: "Variable",
      cashPrize: "Worth ₹2,00,000"
    }
  ],
  "Night Shows": [
    {
      id: 1,
      title: "Concert Night",
      category: "CONCERT",
      description: "Live music performances from popular artists.",
      dateMonth: "DEC",
      dateDay: "15",
      fullDate: "Dec 15, 2026",
      time: "7:00 PM",
      venue: "Amphitheater",
      entryFee: "₹500-1500",
      cashPrize: "N/A"
    },
    {
      id: 2,
      title: "DJ Night",
      category: "DJ NIGHT",
      description: "High-energy electronic music with renowned DJs.",
      dateMonth: "DEC",
      dateDay: "16",
      fullDate: "Dec 16, 2026",
      time: "9:00 PM",
      venue: "Night Club",
      entryFee: "₹800",
      cashPrize: "N/A"
    },
    {
      id: 3,
      title: "Theater Performance",
      category: "THEATER",
      description: "Dramatic stage presentations and theatrical performances.",
      dateMonth: "DEC",
      dateDay: "17",
      fullDate: "Dec 17, 2026",
      time: "8:00 PM",
      venue: "Main Theater",
      entryFee: "₹300-600",
      cashPrize: "N/A"
    },
    {
      id: 4,
      title: "Stargazing Event",
      category: "ASTRONOMY",
      description: "Astronomical observations and celestial wonders.",
      dateMonth: "DEC",
      dateDay: "18",
      fullDate: "Dec 18, 2026",
      time: "10:00 PM",
      venue: "Observatory",
      entryFee: "₹200",
      cashPrize: "N/A"
    },
    {
      id: 5,
      title: "Dance Night",
      category: "DANCE",
      description: "Learn and groove to various dance styles.",
      dateMonth: "DEC",
      dateDay: "19",
      fullDate: "Dec 19, 2026",
      time: "8:30 PM",
      venue: "Dance Floor",
      entryFee: "₹400",
      cashPrize: "N/A"
    }
  ]
};

export default eventData;